### PR TITLE
Update ItemButton.lua

### PR DESCRIPTION
**Pull request by Leoguy77**
As mentioned by andywy119 in issue #503 
Added PawnIsContainerItemAnUpgrade since IsContainerItemAnUpgrade is deprecated in the new pawn version.

### CODE REVIEW

**Comment by Zeffuro** [comment]
Tested it with the newer version of Pawn, I can confirm this fixes the issue.

**Comment by laseryxa** [comment]
I can also confirm, patch works fine

**Review by clmcgrath — APPROVED** [review]

**Comment by clmcgrath** [comment]
tested and confirmed working

**Comment by Leoguy77** [comment]
why is this pull-request not merged? Adibags still doesnt work with the new pawn version

**Comment by Zeffuro** [comment]
I have no idea, they probably don't care enough about implementing an addon specific thing into AdiBags?

**Pull request closed without merging**
