### PR TITLE
Masque support via plugin.

### PR DESCRIPTION
**Pull request by kalbert312**
Adds masque skinning support for item buttons. See commit messages for specific changes.

Using Masque - Caith:
adibags-masque-pic

Video: 
<blockquote class="imgur-embed-pub" lang="en" data-id="a/AYVjDG0"  ><a href="//imgur.com/a/AYVjDG0">AdiBags w/ Masque</a></blockquote>

~Seems to work with basic setup fine though I want to test it more until I move it to review based on looking at an old masque support commit and how it hooks into UpdateBorder and supplies options to masque.~ I've tested it with a week of gaming. Didn't notice any glaring issues.

Aside from masque support, one more notable change was changing junk quality highlight. It will highlight as red now because with dark skins typically have a grey/dark grey border and junk was highlighting with full white which looked odd. Red basically meaning "you should vendor/deal with this". I also separated junk dimming from the quality highlighting effectively making quality highlighting just mean the border color. EDIT: The quality highlight on junk is now a setting (default: OFF)

### CODE REVIEW

**Comment by kalbert312** [comment]
Tested with playing for a week. Also manually tested enabling/disabling masque adibags plugin and masque group skin settings in different scenarios.

**Comment by kalbert312** [comment]
Facing new issue with enable and renable of the plugin. It looks like there might be some pollution from masque on the button. Adibags looks like it keeps around button instances until ui reload so I'm not so sure how I'm going to work around this easily.

**Comment by kalbert312** [comment]
Just noticed that bank item tooltips seem to be wrong... might be related to https://github.com/AdiAddons/AdiBags/pull/467/commits/da4fd0fe1817a307066060ea0b64512b14fa364f

**Comment by kalbert312** [comment]
Ok so I'm not sure I entirely understand the issue but I believe https://github.com/AdiAddons/AdiBags/pull/467/commits/f6c9f15dd3a1c8023744e265d9ec3e53b2c76f3b fixes what I was encountering. My bank item tooltips look to be correct now. I ran the debug command and with a bank of many many items, the BankItemButton pool only had 28 active objects (way less than the number of buttons in my bank container)... I was expecting all bank buttons to be in that pool but it seems not the case.

**Comment by Talyrius** [comment]
This needs to be optional, not the default behavior.
> _Aside from masque support, one more notable change was changing junk quality highlight. It will highlight as red now because with dark skins typically have a grey/dark grey border and junk was highlighting with full white which looked odd. Red basically meaning "you should vendor/deal with this"._

To anyone following this PR, please test these changes and provide feedback.

**Comment by kalbert312** [comment]
Junk highlight toggle added with default value of false. Fixed some more enable/disable bugs. Looks like masque leaves side effects on the button so I'm also cleaning those up. The final complexity of the enable/disable logic makes me think it should just force a reload of the UI... there could be other side effects other than border width/height that I'm not aware of.

**Comment by Talyrius** [comment]
This is what it this PR looks like for me using the latest versions of [Masque](https://www.curseforge.com/wow/addons/masque) and the [Caith skin](https://www.curseforge.com/wow/addons/masque-caith) as used in your example. Any idea where the discrepancy lies?
image

**Comment by kalbert312** [comment]
I haven’t had a chance to test it post merge yet. Since I pushed probably makes sense to close the PR and reopen.

**Comment by kalbert312** [comment]
Thanks for the fix, dunno how I glazed over those. Happens after a long day of work and fatigue. I may fiddle with this soon and get it working again.

**Comment by kalbert312** [comment]
I got a chance to tinker around with this. I'm not too familiar with ItemButton and blizzards intentions with its template, but I think what was going on was some change to `IconQuestTexture`'s lifecycle of some sort. 

Didn't really find the true root cause, but after looking at Masque's Regions (https://github.com/SFX-WoW/Masque/wiki/Regions) and the `ItemButton` template (https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/ItemButtonTemplate.xml)... it looks like quality highlight should be taken care of by the `IconBorder` while the quest stuff should be left to `IconQuestTexture`.

I also switched my "readd the button to masque group" code to use the new `group:ReSkin(button)` masque API as that was my earlier intention.

There's an annoying regression: quality opacity isn't working. Oddly enough when I programmatically set the vertex color on the icon border with a non-1 alpha, it works as expected. I did some print debugging and the alpha being passed to the call is indeed what is coming from the settings panel... something must be resetting the values somehow... dunno.

**Comment by glassleo** [comment]
Has anyone been able to get Masque working for AdiBags since 10.0? I used to edit my local copy with this fix but I can't get it to work now.

**Comment by Cidan** [comment]
Hi everyone,

I'm going to use this PR as a basis for implementing Masque support. This has been a highly requested feature (along with ElvUI support), and I know not having this keeps too many users away.

I'll be working on this over the next few days.

Thanks!

**Comment by Cidan** [comment]
Hey everyone!

Sorry for the delay.

As part of a full effort to revamp the way AdiBags can be themed, I've implemented Masque support from this PR (with a few changes) into a branch called 'theme'. This branch also contains various other theme changes, including an external API for implementing new themes and applying them. I still have a bit more work to do, but Masque support works great.

Thank you to @kalbert312 for the initial implementation!

**Pull request closed without merging**
