### PR TITLE
Show battle pet levels in bags

### PR DESCRIPTION
**Pull request by ntowle**
Currently the item level of "20" is shown for all battle pets in your bags. This PR will change that behavior so the actual level of the battle pet is shown instead.

### CODE REVIEW

**Comment by legowxelab2z8** [comment]
I tested this and it works well. 
Coloring based on the rarity of the pet would be nice. I saw that the first commit had this code commented out was there an problem with setting the color?

It looks like you tried to minimize the impact of your changes to not effect other parts of the code which is normally good. Over the years the update function has become a cludge of hacks for features that were added. Overall I would recommend that the UpdateButton logic be refactored entirely to if / ifelse cases based on objectTable[1] (Item Type)

like
```
--Item Logic
local objectTable = { strsplit(":", string.match(link, "|H(.-)|h")) }
if objectTable[1] == "item" then
	--Item logic
elseif objectTable[1] == "battlepet" then
	--Battlepet logic
end

--Display logic
if not text then
	text = CreateText(button)
end
text:SetText(level)
return text:Show()
```
This would decouple the item specific logic from the display logic and then you wouldn't have to duplicate it for the battlepet case.
Additionally this would allow the logic to be extended to handle other non item cases like MythicKeystones and any other types that blizzard adds later.

I will submit a pull request that refactors the update logic for consideration.

**Comment by ntowle** [comment]
I didn't like coloring pet level by rarity, tried it for a while. It made it harder for me to read the number on certain pet icons. Especially noticeable for rare pets - which is most of the pets that end up in my bags. Since AdiBags already colors the icon border by rarity it seemed redundant as well.

**Comment by legowxelab2z8** [comment]
For @Talyrius and other maintainers
Currently it looks like:
CurrentPetCage
After the change: (notice the level for the battle pets)
NewPetCage

**Comment by ntowle** [comment]
Comparison of level coloring, maybe you can see what I mean by the readability of the rarity-colored levels:

wow pet no color level

wow pet color level

**Comment by legowxelab2z8** [comment]
I like that way of extracting the link information.  I couldn't find any information about it online, but I was able to find it in the interface files.

https://github.com/tomrus88/BlizzardInterfaceCode/blob/63fae122730dcf6cd905072b2d1f7ed203949950/Interface/FrameXML/ItemRef.lua#L531-L539

I like that it is by Blizzard and used in their interface so it is likely to be updated if/when they change the link strings.

It is interesting to see how Blizzard handles battlepets in their own code

https://github.com/tomrus88/BlizzardInterfaceCode/blob/b193986106e8187e7978e99a461d0e11f7d85483/Interface/AddOns/Blizzard_AuctionHouseUI/Blizzard_AuctionHouseTableBuilder.lua#L356-L362

**Comment by Alyred** [comment]
When I update my ItemLevel.lua file with this one (to stock Adibags 1.9.22), it seems that whenever I go through a portal, my itemlevels disappear from the items in my bags.

Before going through the portal (Zuldezar->Orgrimmar, for instance, but also traveling through other zone changes/portals that cause a loading screen):
image

After:
image

Doing a /reloadui does fix the issue, but going through a portal again causes the itemlevels to vanish again.

**Comment by ntowle** [comment]
@Alyred Seems like OnDisable is being called when zoning (for some reason), which causes all texts to hide. Wiping the updateCache in OnDisable seems to be the fix.

**Comment by Alyred** [comment]
I'll plug it in and test it with the other itemlevel, upgradearrow and pawn fix pulls!

**Comment by Alyred** [comment]
Looks good so far!

Now... can you make another pull that does the same for bags in your inventory to show the number of slots instead of the item level? :)

**Comment by ntowle** [comment]
> Looks good so far!
> 
> Now... can you make another pull that does the same for bags in your inventory to show the number of slots instead of the item level? :)

Ha... maybe. This might not be possible without tooltip scanning though, or building a table of known bag IDs and sizes. Probably outside the scope of this PR - although I have made some progress on other improvements to item level display for a future PR.

**Comment by Alyred** [comment]
> > Looks good so far!
> > Now... can you make another pull that does the same for bags in your inventory to show the number of slots instead of the item level? :)
> 
> Ha... maybe. This might not be possible without tooltip scanning though, or building a table of known bag IDs and sizes. Probably outside the scope of this PR - although I have made some progress on other improvements to item level display for a future PR.

Absolutely! I didn't mean to suggest adding it to this PR, but as a thought about a new one, perhaps. ;)

**Comment by ntowle** [comment]
@Talyrius Any chance to get this merged? I have a couple other enhancements to item level display (for conduits/etc) which would depend on these changes.

**Review by Talyrius — CHANGES_REQUESTED** [review]
Most of these change requests are whitespace related:

For comments, add a space after the double hyphen.

**Review by Talyrius — CHANGES_REQUESTED** [review]
The comments still need a space added after the double hyphen.

**Pull request merged**
