### PR TITLE
New Theme Engine

### PR DESCRIPTION
**Pull request by Cidan**
This CL implements an entirely new theme engine for AdiBags, replacing the old 'Skins' option. Users can now individually theme each of the three bag views (Backpack, Bank, and Reagent Bank), and collection of settings can be saved as themes.

We've also implemented an API so that other addons can inject themes into AdiBags, which will allow other addon authors to reskin AdiBags without the need for ugly forks and hacks.

Additionally, this CL also implements full Masque support for the backpack and bank independently, which brings a long requested feature to a close.

### CODE REVIEW

**Comment by Cidan** [comment]
Note: This CL is still a WIP, there are a few things that need to be done, specifically around cleaning up themes, saving/loading themes, etc.

**Comment by Cidan** [comment]
@Talyrius Do you mind doing a quick spot check here? This is a hefty change, but the highlights are:

* Moved away from a single "Skin" option and into a "Theme" tree, with sub settings for bags, bank, and reagent bank.
* Changed some of the default theme settings.
* Fonts can now be changed per-bag, instead of global fonts.
* Full Masque support for buttons, with individual button themes for bank and bag.
* Removed the option for making the bag "anchored", as this is a really poor first-user experience, and is an unusual convention -- bags now move with a click-drag on the header.
* Convert all previous skin options to the new theme settings, so no options are lost on upgrade.
* Changed the defaults for the currency module, so it only shows Honor on first install for new users.
* Set the default scale for new users to 1.0 (from 0.8).

Overall, the goal of this CL is to make changes to the overall visual style of AdiBags so that it has friendlier first time install defaults, and to allow for a much greater degree of customization.

Not that the external theme API is not yet implemented, and will come at a later date.

**Comment by Cidan** [comment]
Update: Added theme creation/saving/loading as an option, with a default theme that can never be edited/removed.

**Comment by Cidan** [comment]
I've done extensive testing on all three versions of WoW, testing pre-existing settings, new installs, and everything inbetween. I'm happy with the way it turned out, so I'm going to go ahead and merge this.

**Comment by Talyrius** [comment]
Sorry, I didn't get a chance to review it. There's certainly a lot to go over here! 😅

**Comment by Cidan** [comment]
No worries! I tested the heck out of it, everything worked as expected, and overall I think I'm pretty happy with the design decisions.

**Pull request merged**
