### PR TITLE
More theme fixes.

### PR DESCRIPTION
**Pull request by Cidan**
This CL fixes a few bugs around the new theme release:

* Fixed a bug where bag colors were not being copied over properly.
* Fixed a bug where quest icon/borders were not being shown when Masque was disabled.

### CODE REVIEW

**Comment by Cidan** [comment]
@Talyrius Can you take a look at this? It struck me while working that `nil` colors were actually just `0`. I wish I knew why it's `nil` in some cases, but another part of me really, really doesn't want to know how it got to be this way.

**Comment by Talyrius** [comment]
> I wish I knew why it's `nil` in some cases, but another part of me really, really doesn't want to know how it got to be this way.

😆

It's because AceDB-3.0 uses metatables in a similar fashion as my previous code example. Only options that differ from their defaults are saved.

**Comment by Cidan** [comment]
Gosh I love working in a language where everything is a reference :p

**Comment by Cidan** [comment]
Alright, I implemented the table from your last comment, double checking to make sure those were the default values previously.

**Review by Talyrius — COMMENTED** [review]
None of the color values are preserved with these changes. All three are set to `{ 0, 0, 0, 1 }`. Will look at subsequent changes.

**Comment by Cidan** [comment]
Okay, pushed another change -- ipairs halts on the first nil encountered, such that nil keys breaks the loop. I inverted the loop so the defaults are looped and compared, and it looks like the defaults now copy over when `nil` is a key in the original setting.

**Review by Talyrius — APPROVED** [review]

**Pull request merged**
