### PR TITLE
Fixed errors in TWW client.

### LINKED ISSUE #1012: 11.0 updates
### Describe the feature

I know the addon is discontinued but has anyone been able to get it to work in the new patch? I can kinda get it to work after removing the interface panel button and adding a dummy function in ItemButton.lua:

```lua
function buttonProto:ENCHANT_SPELL_COMPLETED(...)
end
```

... but I'm not smart enough to figure out why every single item button is just blank with no stack text, cooldowns not showing, and textures only working with Masque (and not at all without).

### Describe the implementation

Anyone smart who can get it in a somewhat working state?

### PR DESCRIPTION
**Pull request by Pegoth**
Fixed errors after TWW client update.

fixes #1012

### CODE REVIEW

**Comment by customlibs** [comment]
With this fix, it works perfectly, thank you !

**Comment by glassleo** [comment]
For me it's... sometimes working? Sometimes all my bags are just empty blue boxes and sometimes it works after waiting for like 2 minutes after logging in. Then when I reload it's broken again.

**Comment by glassleo** [comment]
image

**Comment by Pegoth** [comment]
My friends don't use any bag addon and it does not work for them sometimes, so the image is not AdiBags related, I think. Did you get any lua error?

**Comment by glassleo** [comment]
No lua errors. I think it gets fixed whenever ``ENCHANT_SPELL_COMPLETED`` is triggered (which happens randomly in Valdrakken when people around you enchant gear). I can reliably "fix" it by enchanting one of my own items.

**Comment by glassleo** [comment]
Yep, addon breaks after /reload or relog until someone around me enchants an item, then all buttons are "refreshed" and look normal. If I get a new item, that item's button is broken (no texture, no stack text, weird blue border)

**Comment by glassleo** [comment]
The search bar is also not working, it's not dimming any items

**Comment by Syrrion** [comment]
No issue for me about blue boxes, but search don't work for me too

**Comment by glassleo** [comment]
If you stand in a busy Valdrakken where people are constantly enchanting items it may seem like it's working even if it's really not.

**Comment by Pegoth** [comment]
No issue for me either with the blue boxes, I even flew away into a remote area and still no issue. The search doesn't work for me either, but I think that is a blizzard feature (which is bugged), so I didn't touch it.

**Comment by glassleo** [comment]
I was able to get the search to work after enchanting an item, it refreshed. I think it's because the ``ENCHANT_SPELL_COMPLETED`` triggers all buttons to do a full update.

**Comment by glassleo** [comment]
A very hacky and bad (but kinda working) solution is to add this delayed full update in buttonProto:OnAcquire:

```lua
C_Timer.After(0.1, function() self:FullUpdate() end)
```

It seems that for whatever reason buttons are not updated when they are created, or they are overwritten 1 frame after updating. I don't know what is causing it.

**Comment by glassleo** [comment]
Doesn't solve search though...

**Comment by Pegoth** [comment]
Found the bug, OnShow is never called, checking why...

**Comment by glassleo** [comment]
Maybe something with the button template changed?

**Comment by glassleo** [comment]
moving all the event registering from OnShow to OnAcquire seems to fix most issues

**Comment by Pegoth** [comment]
Yeah, it seems like the ContainerFrameItemButtonTemplate now has OnShow and OnHide functions by default, renaming the custom functions fixed the issue, committing fix soon.

**Comment by glassleo** [comment]
> Yeah, it seems like the ContainerFrameItemButtonTemplate now has OnShow and OnHide functions by default, renaming the custom functions fixed the issue, committing fix soon.

Aha!

**Comment by glassleo** [comment]
> Done, can you check if it fully works now for you? @glassleo

Works perfectly. I love you. No hacks needed, search works, Masque works, balance has been restored to the world.

**Comment by Munno22** [comment]
> Fixed errors after TWW client update.
> 
> fixes #1012

Hey @Pegoth , I've also been updating AdiBags myself & I fixed the 
`hooksecurefunc('TokenFrame_Update', function() self:Update() end)`
 line in modules/CurrencyFrame.lua by changing it to 
`hooksecurefunc(TokenFrameMixin,'Update', function() self:Update() end)`
 instead of your solution. Is your solution the proper way of doing things now? Idk what I'm doing but I'm really curious as to what the differences are lol

sorry for random question!

**Comment by Pegoth** [comment]
@Munno22 I have no idea what TokenFrameMixin does, the function supposed to update stuff when currency changes (I think, I didn't look that deep), that is why I opted for events instead.

**Review by acx-nvstar — APPROVED** [review]

**Review by acx-nvstar — APPROVED** [review]
This is works very well for TWW Pre-Patch

**Comment by Nyuwb** [comment]
LGTM

**Comment by Talyrius** [comment]
Fixes implemented via a9a573c. Thanks for the PR, it made the job easier.

**Pull request closed without merging**
