### PR TITLE
Resolve issues with new container APIs

### PR DESCRIPTION
**Pull request by jnwhiteh**
The container APIs on 10.0.2 have moved into C_Container and a few functions have been outright removed.

In addition the returns for GetContainerItemInfo and GetContainerItemQuestInfo have changed to use tables instead of a long list of returns.

This introduces a set of wrapper functions to handle working with both the new C_Container APIs and the legacy APIs to support wrath and classic-era.

### CODE REVIEW

**Comment by Cidan** [comment]
Hey @jnwhiteh -- thank you for the CL!

Have you confirmed this works in all current versions of WoW on the market? Also, can you update the two TOC files for retail?

Thanks!

**Comment by jnwhiteh** [comment]
I don't have a full test suite but I've tested on I've tested on classic-era, wrath-classic, and dragonflight, but only overall cursory testing. In particular I've tested viewing the inventory, looking at the bag slots, bank and reagents. I've also tested with Adibags_Shadowlands and that's still working too.

I'm not 100% on the tooltip hooking change, as the payloads are apparently different. I can either just let that fail silently or leave it as it is, entirely open to direction there. Wasn't super sure what that was doing, but could try to look tomorrow.

This is probably good for an alpha channel release if nothing else, as it fixes what's broken.

**Comment by picklerick84** [comment]
Hello,
Idk if this is the right play to put this, as I have little coding experience and just learning.  I managed to fix a couple addons myself and was looking at this until I seen @jnwhiteh commits and I went ahead and made all the changes he made in game right now.  It does fix pretty much everything on retail and gets rid of errors in bugsack.  Only a couple issues still so far:

1) The item count in bags doesn't update at all or show any count for items
2) The glow on items in bags is gone now

Also, not your problem.  It messes with pawn, but I went and added the C_Container changed and it fixed it.  Not your problem anyway.

**Comment by jnwhiteh** [comment]
Hey @picklerick84 I can't confirm the first issue at least. When I load my inventory I've got stack counts, and if I use a sharpening stone the count goes down as expected.

**Comment by jnwhiteh** [comment]
Thanks @picklerick84, it seems like I removed some code when I was cleaning up before submitting. Was an easy two-line fix to resolve the issue with stackCounts. I also found an issue with search filtering and was able to resolve that.

image

**Comment by Cidan** [comment]
LGTM -- I'm going to merge this, and other fixes in the future should rebase off of the main branch.

Thank you @jnwhiteh -- I am extremely, extremely grateful for your help here!

**Review by Ch3yenne13 — COMMENTED** [review]
gh pr checkout 788

**Pull request merged**
