### PR TITLE
Correct typo 'mechants' to 'merchants'

### PR DESCRIPTION
**Pull request by andschwa**
Feel free to squash/cherry-pick.

### CODE REVIEW

**Comment by Cidan** [comment]
At the top of the file there is a comment that notes that Localization changes are auto generated here:

http://www.wowace.com/addons/adibags/localization/

Please feel free to make the changes there.

**Comment by andschwa** [comment]
Ah the pitfalls of a simple grep | xargs sed.

**Comment by andschwa** [comment]
@Cidan I feel like a moron. I found the [localization set](https://www.wowace.com/addons/adibags/localization/phrases/265-at-mechants-bank-auction-house/) and made an account, but how the heck do I edit it?

**Comment by Talyrius** [comment]
I'm pretty sure @Adirelle is the only one that can create/modify english phrases as it's the project's primary language and no else has been given appropriate permissions at WowAce.

**Comment by andschwa** [comment]
@Adirelle is there any way I can fix some of the English localizations?

**Comment by Talyrius** [comment]
I have the ability to do so now. Are there others?

**Comment by andschwa** [comment]
Awesome!

- [that allow to hide](https://www.wowace.com/addons/adibags/localization/phrases/222-add-a-dropdown-menu-to-bags-that-allow-to-hide-the/) -> that allows you to hide

- [Allow you manually](https://www.wowace.com/addons/adibags/localization/phrases/3-allow-you-manually-redefine-the-section-in-which-an/) -> Allows you to manually

- [this section ?](https://www.wowace.com/addons/adibags/localization/phrases/247-are-you-sure-you-want-to-remove-this-section/) -> this section? (there are a lot like this...)

- [merchant's, bank, ...](https://www.wowace.com/addons/adibags/localization/phrases/314-automatically-open-the-bags-at-merchants-bank/) -> merchants, bank, ...

- [merchants'](https://www.wowace.com/addons/adibags/localization/phrases/236-change-stacking-at-merchants-auction-house-bank-mailboxes/) -> merchants

- [are dispatched in](https://www.wowace.com/addons/adibags/localization/phrases/203-check-this-so-armors-are-dispatched-in-four-sections/) -> are displayed in

- [display an textual](https://www.wowace.com/addons/adibags/localization/phrases/18-check-this-to-display-an-textual-tag-before-usage-of/) -> display a textual

- [considered as junk](https://www.wowace.com/addons/adibags/localization/phrases/256-items-in-this-list-are-always-considered-as-junk-click/) and [considered as junk](https://www.wowace.com/addons/adibags/localization/phrases/257-items-in-this-list-are-never-considered-as-junk-click/) -> considered junk

- [filter matchs](https://www.wowace.com/addons/adibags/localization/phrases/69-please-note-this-filter-matchs-every-item-any-filter/) -> filter matches

- [Provides a LDB](https://www.wowace.com/addons/adibags/localization/phrases/72-provides-a-ldb-data-source-to-be-displayed-by-ldb-display/) -> Provides an LDB

- [positionned](https://www.wowace.com/addons/adibags/localization/phrases/310-select-how-the-bags-are-positionned/) -> positioned

- [should be dispatched](https://www.wowace.com/addons/adibags/localization/phrases/167-select-the-sections-in-which-the-items-should-be-dispatched/) -> should be displayed

- [Show every distinct item stacks.](https://www.wowace.com/addons/adibags/localization/phrases/243-show-every-distinct-item-stacks/) -> Show each distinct item stack.

- [each kind of bags.](https://www.wowace.com/addons/adibags/localization/phrases/229-show-only-one-free-slot-for-each-kind-of-bags/) -> each kind of bag.

- [auto-deposit ponctually by](https://www.wowace.com/addons/adibags/localization/phrases/359-you-can-block-auto-deposit-ponctually-by-pressing-a/) -> auto-deposit manually by

That should cover most of it (ignoring inconsistent period/ellipses/etc. usage, and the fact that I just did a quick lookover).

**Pull request closed without merging**
