### PR TITLE
WoW Classic compatibility

### PR DESCRIPTION
**Pull request by jbjt**
Hi,

Obviously I don't expect this to be merged into master (ideally it'd be a new branch), but I wanted to share what I did to get this fantastic AddOn working in Classic.

The modern parts of patch 1.13.2 are based on the 8.1.0 API, so this conversion has been done with the libraries which target that version, namely:
- Ace3 r1200
- AceGUI-3.0-SharedMediaWidgets r61
- BugGrabber v8.2.0 (This one obviously targets 8.2 but it works without issue)

I don't know how the library bundling process works but in my own fork I've made a separate branch called [classic-bundle](https://github.com/jbjt/AdiBags/tree/classic-bundle) which includes these libraries for ease of testing and distribution to my guild mates who were interested.

Most interesting to note here is that with the loss of GetContainerItemQuestInfo, the Quest Items filter probably isn't doing anything that the base Item Category filter won't cover. As I'm not 100% sure on what I'm doing though, I decided to leave it in.

### CODE REVIEW

**Comment by amey1956** [comment]
using the version d/l above i get this error from bug grabber:
6x Error loading AdiBags\libs\LibDataBroker-1.1\LibDataBroker-1.1-4.lua 

also in chat: Couldn't open Interface\Addons\AdiBags\libs\BugGrabber\load.xml repeated 2 more times

**Comment by jbjt** [comment]
Sorry I'm not at my computer to fix it, but assuming everything is installed correctly, try going into the AdiBags/lib folder and renaming the !BugGrabber folder to BugGrabber, removing the exclamation mark. I'm not sure how that was working for me!

**Comment by amey1956** [comment]
thanks for the response - i made the changes above and just as i was about to log in to check - servers gone :( 

soon ;)

**Comment by hardtofin** [comment]
hi JBJT

are you going to continue work on this addon to get it fully working in classic?  I can't live without it!

Many thanks!

**Comment by jbjt** [comment]
Hi all, I've updated the classic-bundle branch on my fork to pull in the LibDataBroker addon without using a submodule (so Download ZIP works), and to rename the BugGrabber folder. Obviously I can't test this right now but I believe it should fix the issues reported above. I didn't actually test the LDB functionality which is why I didn't notice that wasn't working, an oversight on my part. I'll be sure to test it once we're all back in-game!

Again, for interested parties who want a quick working addon right now, go to my [classic-bundle](https://github.com/jbjt/AdiBags/tree/classic-bundle) branch and **follow the installation instructions** :)

**Comment by jukx** [comment]
Hi @jbjt thanks so much for making AdiBags work on Classic!

What do you think about creating a real release (zip) and providing it at one of the popular addon databases (WOWI or Curse) so that more people can enjoy this awesome addon?

**Comment by hardtofin** [comment]
hi @jbjt There is an error in adibags classic which is showing weird item counts for items.  So it is showing that you have say 10 of something when you only actually have 1.
I had this this morning with a 10 pound mudfish.

thanks!

**Comment by jbjt** [comment]
@jukx I'd prefer for the maintainer to release an official version, but I may do that at some point if that doesn't happen - I'd rather be playing the game than anything else at this point!

@hardtofin This number is the item level. Since the 10 pound mud snapper is an equippable item it has an item level! Item level isn't all that useful in classic though, so you might just want to disable the Item level plugin within the AdiBags config.

**Pull request merged**
