### PR TITLE
Updating for 9.0.1

### PR DESCRIPTION
**Pull request by RipeTomatoe**
Updating all call sites where small API changes happened. 
 - Only adding the Background Templates to Frames that needed it (to adhere to the standards presented by Blizz)
 - Changing all enums over
 - Using the structure for currency functions

### CODE REVIEW

**Comment by tcprescott** [comment]
I packaged and installed this version, and it works swimmingly for me.  Thanks!

**Comment by t-mart** [comment]
I'm undertaking the same endeavor on [my fork](https://github.com/t-mart/AdiBags). Haven't PR-ed, and looking at this, I probably won't because it's almost the same, and then some.

One thing I think you're forgetting is to bump TOC version in https://github.com/RipeTomatoe/AdiBags/blob/master/AdiBags_Config/AdiBags_Config.toc#L1. WoW will claim out-of-date for it otherwise.

**Comment by Starfighter7201** [comment]
How exactly do I download and install this to update?

**Comment by RipeTomatoe** [comment]
Right, yea I forgot the TOC in configs.
Also I'm not exactly sure how you could download and update, as for the differences, it's more of a "bugfix" approach rather than changing whole systems to work with API changes. I actually didn't check other fork's before posting this one, I just fixed it for myself and some friends, and decided to drop it here in case anyone needed some reference.

**Comment by dansledge** [comment]
Installed and tested for a few hours now. Working great. It just needs the version changed so the game doesn't mark it as out of date. I was suffering without this! Great job! Thanks!

**Comment by Taumer** [comment]
Table with items level should be updated too. Without this doest'n showing ilvl for items in bags
https://github.com/AdiAddons/AdiBags/blob/master/modules/ItemLevel.lua#L316
Version in TOC must be `90001` instead  of `90100` 
After this addon will be working like a charm

**Comment by RipeTomatoe** [comment]
Oh boy, that ItemLevel lua seems like it can be completely gutted, since all xpacs are 1-50, and we'd only need a separate entry for Shadowlands at 50-60

**Pull request closed without merging**
